# Generated by Django 3.0.8 on 2020-08-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120, verbose_name='name')),
                ('evaluation', models.TextField(blank=True, verbose_name='like it or not?')),
                ('email', models.TextField(blank=True, verbose_name='email')),
                ('message', models.CharField(max_length=120, verbose_name='advice')),
            ],
        ),
    ]
