# Generated by Django 3.0.8 on 2020-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20200830_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='evaluation',
            field=models.BooleanField(null=True, verbose_name='I like this page！'),
        ),
    ]
